### PR TITLE
Refactor rake tasks into harvester and indexer classes

### LINKED ISSUE #112: Support ingesting metadata using either geoblacklight.json or <ID>.json
Currently, OGM allows for two styles of naming. One is to have all of your metadata in folders (usually some sort of pair tree), and the file itself is just named geoblacklight.json (see Stanford). However, a fair amount of people don't use this naming convention and instead just have a few directories of files with <ID>.json (see Harvard). 

This involves allowing any '*.json', but excluding explicitly layers.json (which is a standard file under the Stanford model)

### LINKED ISSUE #119: Update logic for 'all repos' cloning/indexing tasks
Currently, the logic for indexing when no specific repo is specified is to pull all repositories with edu.*, uk.*, or org.* and anything in the allowlist (currently only big10). If orgs have made their repositories and didn't follow this, they are being excluded. The proposal is to either

1) Default to indexing everything unless it is on a deny list (don't do the explicit allow check)
2) Implement a tagging system where a repository whose owner would like it included uses the tag 'datasource'
    * Note that if we use tags we'll need to ask everyone to tag their repositories to maintain existing functionality

### LINKED ISSUE #130: Support filtering records to index based on schema version
related to #105.

for folks not using aardvark, we want to support the possibility of harvesting scoped to earlier schema versions. the "simple" way to do this is just e.g. looking for `/aardvark/` in the path and asking folks to put their records in an "aardvark" folder, but ideally we would do it the "smart" way and actually look at the schema version in the record at the point we see the record. if this isn't possible for performance reasons, we can fall back to the "simple" strategy.

### PR DESCRIPTION
**Pull request by thatbudakguy**
This mostly moves logic out of rake tasks and into dedicated classes, which makes it easier to test. It also separates the harvesting portion from the indexing portion; this might make it easier to have the geoblacklight harvester inherit some of this behavior later. The denylist is one of the things the harvester class includes, which closes #119. I think the logic mentioned in #112 was already in place, so this closes #112 too.

It also adds logic to filter indexing based on your desired schema version (set `SCHEMA_VERSION` to `Aardvark` to index only aardvark records; the default is 1.0), which fixes #130.

I added a dependency on ruby-git to do the git pull/clone instead of just calling out to `system()`, which made things easier to test and might also allow for things to run on windows.

### CODE REVIEW

**Comment by thatbudakguy** [comment]
blocked by #134 and #135

**Comment by eliotjordan** [comment]
@thatbudakguy  I merged #135. Try rebasing this branch against main.

**Comment by thatbudakguy** [comment]
rebased — rubocop is happy now, but I think we need #134 in order for this to pass

**Comment by eliotjordan** [comment]
@thatbudakguy Done. Try rebasing agagin.

**Comment by thatbudakguy** [comment]
ah, SimpleCov is (rightly) complaining that I didn't write any tests for the indexer! I'll do that...

**Comment by thatbudakguy** [comment]
all set now.

**Review by eliotjordan — APPROVED** [review]
Looks great!  💯

**Pull request merged**
