### PR TITLE
adds support for Esri OpenData portal metadata conversion to GeoBlack…

### PR DESCRIPTION
**Pull request by mejackreed**
…light

 - also adds mixin `Formatting` for sanitizing strings

Metadata can be found in http://opendata.arcgis.com/ and you can use the `.json` extension on urls to get json metadata back

### CODE REVIEW

**Comment by mejackreed** [comment]
Lazy concensus....

**Comment by eliotjordan** [comment]
@mejackreed I had this PR open as a tab all last week meaning to comment. Apologies. This looks good, except that we haven't (as far as I know) made a final decision on how to handle dct_ref(s) for the ArcGIS REST API. I've carved some time this week to work on that. I'll go and give those threads a dap :punch:.

**Comment by mejackreed** [comment]
Awesome @eliotjordan ... I've still been thinking about the geoblacklight support... Let's talk this week about how to get that in.

**Comment by eliotjordan** [comment]
Yep. Lets get this done!

**Pull request merged**
