### PR TITLE
Add tasks and abstraction

### PR DESCRIPTION
**Pull request by ammonshepherd**
This request adds three new rake tasks: 
- clean: to delete the tmp directory
- delete: to delete the Solr index
- all: combines clone and index for easier first time use

Also, abstracts the Solr URL for better handling of alternative Solr installations. Use of an .env file is supported, as well as adding the URL to the rake tasks (index, delete, and all).

Additionally, the --verbose flag can be used to see output.

### CODE REVIEW

**Comment by mejackreed** [comment]
Thanks for the contribution.

A couple of comments before it can be merged.

1. Could you please rebase your branch against master and fix any merge conflicts?
1. I'm a bit concerned about the `clean` command. Specifically if GeoCombine is used in another application (Rails app/GeoBlacklight) this would probably create some unintended consequences for someone running this command. Maybe we should separate geocombine as a whole?

Maybe something like `tmp/geocombine/edu.institution`

Then `rake geocombine:clean` would just rm -rf `tmp/geocombine`

**Comment by mejackreed** [comment]
Updated default location to be `tmp/opengeometadata` with https://github.com/OpenGeoMetadata/GeoCombine/pull/20

**Comment by mejackreed** [comment]
Thanks looks great! Two additional questions came up as I was looking at this again,

 1. Is there a way we can get around including the dotenv gem dependency? This project aims to be a gem that can be included in other projects. This added dependency may add complications to this. Would something like this be sufficient?

  ```
  solr_url = ENV['SOLR_URL'] || 'http://127.0.0.1:8983/solr'
  ```
 1. I'm still a bit weary of the `rake geocombine:delete` task (and all of the Solr tasks). They start to feel a bit like they are out of scope for this tool and I'm concerned about the potential for adding this into their project (GeoBlacklight) and accidentally deleting a Solr index.

I envision that GeoCombine will soon be a dependency in GeoBlacklight and I'm unsure if these indexing tasks are even appropriate (I know I was the one who added them to start with :smile_cat: ). What are your thoughts on this @mossiso ?

**Comment by mossiso** [comment]
Those are great points. We are using it mainly from the command line, so I built it with that in mind, but you're right, it would be better to take out the dotenv requirement and the delete task to make it more interoperable in other workflows. I don't really know the larger scope and design for GeoCombine/GeoBlacklight (just how we're implementing it for now). 

I'll work on taking out the dotenv and the delete task.

**Comment by thatbudakguy** [comment]
closing this, since it's over 8 years old.

**Pull request closed without merging**
